#!/bin/bash -l 
#SBATCH -A mp309
#SBATCH -C haswell
#SBATCH -p debug
#SBATCH -N 1
#SBATCH -t 00:10:00 
#SBATCH -J one-upc-large
#SBATCH -o one-upc-large.%j.out
#SBATCH -e one-upc-large.%j.err


# Specify path to your input file here
INPUT=large.txt
OUTPUT=restult.txt

cd ${PWD}
srun -n 1 -shared-heap=1G ./kmer_hash $SCRATCH/my_datasets/${INPUT} -s ${OUTPUT}
srun -n 2 -shared-heap=1G ./kmer_hash $SCRATCH/my_datasets/${INPUT} -s ${OUTPUT}
srun -n 4 -shared-heap=1G ./kmer_hash $SCRATCH/my_datasets/${INPUT} -s ${OUTPUT}
srun -n 8 -shared-heap=1G ./kmer_hash $SCRATCH/my_datasets/${INPUT} -s ${OUTPUT}
srun -n 16 -shared-heap=1G ./kmer_hash $SCRATCH/my_datasets/${INPUT} -s ${OUTPUT}
srun -n 32 -shared-heap=1G ./kmer_hash $SCRATCH/my_datasets/${INPUT} -s ${OUTPUT}

